// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: user_query.proto

package user_query_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERR_CODE_USER_QUERY_SERVICE int32

const (
	ERR_CODE_USER_QUERY_SERVICE_CODE_NO_ERROR_USER_QUERY_SERVICE          ERR_CODE_USER_QUERY_SERVICE = 0
	ERR_CODE_USER_QUERY_SERVICE_CODE_ERR_MISSING_PARAM_USER_QUERY_SERVICE ERR_CODE_USER_QUERY_SERVICE = -1
	ERR_CODE_USER_QUERY_SERVICE_CODE_ERR_INVALID_PARAM_USER_QUERY_SERVICE ERR_CODE_USER_QUERY_SERVICE = -2
	ERR_CODE_USER_QUERY_SERVICE_CODE_ERR_UNKNOWN_USER_QUERY_SERVICE       ERR_CODE_USER_QUERY_SERVICE = -1001
)

// Enum value maps for ERR_CODE_USER_QUERY_SERVICE.
var (
	ERR_CODE_USER_QUERY_SERVICE_name = map[int32]string{
		0:     "CODE_NO_ERROR_USER_QUERY_SERVICE",
		-1:    "CODE_ERR_MISSING_PARAM_USER_QUERY_SERVICE",
		-2:    "CODE_ERR_INVALID_PARAM_USER_QUERY_SERVICE",
		-1001: "CODE_ERR_UNKNOWN_USER_QUERY_SERVICE",
	}
	ERR_CODE_USER_QUERY_SERVICE_value = map[string]int32{
		"CODE_NO_ERROR_USER_QUERY_SERVICE":          0,
		"CODE_ERR_MISSING_PARAM_USER_QUERY_SERVICE": -1,
		"CODE_ERR_INVALID_PARAM_USER_QUERY_SERVICE": -2,
		"CODE_ERR_UNKNOWN_USER_QUERY_SERVICE":       -1001,
	}
)

func (x ERR_CODE_USER_QUERY_SERVICE) Enum() *ERR_CODE_USER_QUERY_SERVICE {
	p := new(ERR_CODE_USER_QUERY_SERVICE)
	*p = x
	return p
}

func (x ERR_CODE_USER_QUERY_SERVICE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERR_CODE_USER_QUERY_SERVICE) Descriptor() protoreflect.EnumDescriptor {
	return file_user_query_proto_enumTypes[0].Descriptor()
}

func (ERR_CODE_USER_QUERY_SERVICE) Type() protoreflect.EnumType {
	return &file_user_query_proto_enumTypes[0]
}

func (x ERR_CODE_USER_QUERY_SERVICE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERR_CODE_USER_QUERY_SERVICE.Descriptor instead.
func (ERR_CODE_USER_QUERY_SERVICE) EnumDescriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{0}
}

type CoinOwnershipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *CoinOwnershipRequest) Reset() {
	*x = CoinOwnershipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinOwnershipRequest) ProtoMessage() {}

func (x *CoinOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinOwnershipRequest.ProtoReflect.Descriptor instead.
func (*CoinOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *CoinOwnershipRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetRecentHeadersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetRecentHeadersRequest) Reset() {
	*x = GetRecentHeadersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentHeadersRequest) ProtoMessage() {}

func (x *GetRecentHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentHeadersRequest.ProtoReflect.Descriptor instead.
func (*GetRecentHeadersRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecentHeadersRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type CoinOwnershipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *CommonRspHeaderUserQueryService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Address []byte                           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *CoinOwnershipResponse) Reset() {
	*x = CoinOwnershipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoinOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoinOwnershipResponse) ProtoMessage() {}

func (x *CoinOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoinOwnershipResponse.ProtoReflect.Descriptor instead.
func (*CoinOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{2}
}

func (x *CoinOwnershipResponse) GetHeader() *CommonRspHeaderUserQueryService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CoinOwnershipResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type GetRecentHeadersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header           *CommonRspHeaderUserQueryService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncdedHeaderList []byte                           `protobuf:"bytes,2,opt,name=encded_header_list,json=encdedHeaderList,proto3" json:"encded_header_list,omitempty"`
}

func (x *GetRecentHeadersResponse) Reset() {
	*x = GetRecentHeadersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentHeadersResponse) ProtoMessage() {}

func (x *GetRecentHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentHeadersResponse.ProtoReflect.Descriptor instead.
func (*GetRecentHeadersResponse) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecentHeadersResponse) GetHeader() *CommonRspHeaderUserQueryService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetRecentHeadersResponse) GetEncdedHeaderList() []byte {
	if x != nil {
		return x.EncdedHeaderList
	}
	return nil
}

type CommonRspHeaderUserQueryService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CommonRspHeaderUserQueryService) Reset() {
	*x = CommonRspHeaderUserQueryService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRspHeaderUserQueryService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRspHeaderUserQueryService) ProtoMessage() {}

func (x *CommonRspHeaderUserQueryService) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRspHeaderUserQueryService.ProtoReflect.Descriptor instead.
func (*CommonRspHeaderUserQueryService) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{4}
}

func (x *CommonRspHeaderUserQueryService) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *CommonRspHeaderUserQueryService) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_user_query_proto protoreflect.FileDescriptor

var file_user_query_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x31,
	0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x6b, 0x0a, 0x15, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x82,
	0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x12, 0x65, 0x6e, 0x63, 0x64, 0x65, 0x64, 0x5f,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x64, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x2a, 0xe5, 0x01, 0x0a, 0x1b, 0x45, 0x52, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45,
	0x12, 0x24, 0x0a, 0x20, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x36, 0x0a, 0x29, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45,
	0x52, 0x52, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d,
	0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56,
	0x49, 0x43, 0x45, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x36,
	0x0a, 0x29, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x51, 0x55,
	0x45, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0xfe, 0xff, 0xff, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x30, 0x0a, 0x23, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45,
	0x52, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x97, 0xf8,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0x9b, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a,
	0x0d, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x12, 0x15,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65,
	0x72, 0x73, 0x68, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_user_query_proto_rawDescOnce sync.Once
	file_user_query_proto_rawDescData = file_user_query_proto_rawDesc
)

func file_user_query_proto_rawDescGZIP() []byte {
	file_user_query_proto_rawDescOnce.Do(func() {
		file_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_query_proto_rawDescData)
	})
	return file_user_query_proto_rawDescData
}

var file_user_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_query_proto_goTypes = []interface{}{
	(ERR_CODE_USER_QUERY_SERVICE)(0),        // 0: ERR_CODE_USER_QUERY_SERVICE
	(*CoinOwnershipRequest)(nil),            // 1: CoinOwnershipRequest
	(*GetRecentHeadersRequest)(nil),         // 2: GetRecentHeadersRequest
	(*CoinOwnershipResponse)(nil),           // 3: CoinOwnershipResponse
	(*GetRecentHeadersResponse)(nil),        // 4: GetRecentHeadersResponse
	(*CommonRspHeaderUserQueryService)(nil), // 5: CommonRspHeaderUserQueryService
}
var file_user_query_proto_depIdxs = []int32{
	5, // 0: CoinOwnershipResponse.header:type_name -> CommonRspHeaderUserQueryService
	5, // 1: GetRecentHeadersResponse.header:type_name -> CommonRspHeaderUserQueryService
	1, // 2: UserQueryService.CoinOwnership:input_type -> CoinOwnershipRequest
	2, // 3: UserQueryService.GetRecentHeaders:input_type -> GetRecentHeadersRequest
	3, // 4: UserQueryService.CoinOwnership:output_type -> CoinOwnershipResponse
	4, // 5: UserQueryService.GetRecentHeaders:output_type -> GetRecentHeadersResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_query_proto_init() }
func file_user_query_proto_init() {
	if File_user_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinOwnershipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentHeadersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoinOwnershipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentHeadersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRspHeaderUserQueryService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_query_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_query_proto_goTypes,
		DependencyIndexes: file_user_query_proto_depIdxs,
		EnumInfos:         file_user_query_proto_enumTypes,
		MessageInfos:      file_user_query_proto_msgTypes,
	}.Build()
	File_user_query_proto = out.File
	file_user_query_proto_rawDesc = nil
	file_user_query_proto_goTypes = nil
	file_user_query_proto_depIdxs = nil
}
