// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: user_query.proto

package user_query_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserQueryServiceClient is the client API for UserQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserQueryServiceClient interface {
	CoinOwnership(ctx context.Context, in *CoinOwnershipRequest, opts ...grpc.CallOption) (*CoinOwnershipResponse, error)
	GetRecentHeaders(ctx context.Context, in *GetRecentHeadersRequest, opts ...grpc.CallOption) (*GetRecentHeadersResponse, error)
}

type userQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserQueryServiceClient(cc grpc.ClientConnInterface) UserQueryServiceClient {
	return &userQueryServiceClient{cc}
}

func (c *userQueryServiceClient) CoinOwnership(ctx context.Context, in *CoinOwnershipRequest, opts ...grpc.CallOption) (*CoinOwnershipResponse, error) {
	out := new(CoinOwnershipResponse)
	err := c.cc.Invoke(ctx, "/UserQueryService/CoinOwnership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userQueryServiceClient) GetRecentHeaders(ctx context.Context, in *GetRecentHeadersRequest, opts ...grpc.CallOption) (*GetRecentHeadersResponse, error) {
	out := new(GetRecentHeadersResponse)
	err := c.cc.Invoke(ctx, "/UserQueryService/GetRecentHeaders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserQueryServiceServer is the server API for UserQueryService service.
// All implementations must embed UnimplementedUserQueryServiceServer
// for forward compatibility
type UserQueryServiceServer interface {
	CoinOwnership(context.Context, *CoinOwnershipRequest) (*CoinOwnershipResponse, error)
	GetRecentHeaders(context.Context, *GetRecentHeadersRequest) (*GetRecentHeadersResponse, error)
	mustEmbedUnimplementedUserQueryServiceServer()
}

// UnimplementedUserQueryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserQueryServiceServer struct {
}

func (UnimplementedUserQueryServiceServer) CoinOwnership(context.Context, *CoinOwnershipRequest) (*CoinOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CoinOwnership not implemented")
}
func (UnimplementedUserQueryServiceServer) GetRecentHeaders(context.Context, *GetRecentHeadersRequest) (*GetRecentHeadersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentHeaders not implemented")
}
func (UnimplementedUserQueryServiceServer) mustEmbedUnimplementedUserQueryServiceServer() {}

// UnsafeUserQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserQueryServiceServer will
// result in compilation errors.
type UnsafeUserQueryServiceServer interface {
	mustEmbedUnimplementedUserQueryServiceServer()
}

func RegisterUserQueryServiceServer(s grpc.ServiceRegistrar, srv UserQueryServiceServer) {
	s.RegisterService(&UserQueryService_ServiceDesc, srv)
}

func _UserQueryService_CoinOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).CoinOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserQueryService/CoinOwnership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).CoinOwnership(ctx, req.(*CoinOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserQueryService_GetRecentHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentHeadersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserQueryServiceServer).GetRecentHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserQueryService/GetRecentHeaders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserQueryServiceServer).GetRecentHeaders(ctx, req.(*GetRecentHeadersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserQueryService_ServiceDesc is the grpc.ServiceDesc for UserQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserQueryService",
	HandlerType: (*UserQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CoinOwnership",
			Handler:    _UserQueryService_CoinOwnership_Handler,
		},
		{
			MethodName: "GetRecentHeaders",
			Handler:    _UserQueryService_GetRecentHeaders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_query.proto",
}
