// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: bonus_service.proto

package bonus_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AIAccountService_GetBonus_FullMethodName = "/AIAccountService/GetBonus"
)

// AIAccountServiceClient is the client API for AIAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIAccountServiceClient interface {
	GetBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*BonusResponse, error)
}

type aIAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAccountServiceClient(cc grpc.ClientConnInterface) AIAccountServiceClient {
	return &aIAccountServiceClient{cc}
}

func (c *aIAccountServiceClient) GetBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*BonusResponse, error) {
	out := new(BonusResponse)
	err := c.cc.Invoke(ctx, AIAccountService_GetBonus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAccountServiceServer is the server API for AIAccountService service.
// All implementations must embed UnimplementedAIAccountServiceServer
// for forward compatibility
type AIAccountServiceServer interface {
	GetBonus(context.Context, *BonusRequest) (*BonusResponse, error)
	mustEmbedUnimplementedAIAccountServiceServer()
}

// UnimplementedAIAccountServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAIAccountServiceServer struct {
}

func (UnimplementedAIAccountServiceServer) GetBonus(context.Context, *BonusRequest) (*BonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBonus not implemented")
}
func (UnimplementedAIAccountServiceServer) mustEmbedUnimplementedAIAccountServiceServer() {}

// UnsafeAIAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAccountServiceServer will
// result in compilation errors.
type UnsafeAIAccountServiceServer interface {
	mustEmbedUnimplementedAIAccountServiceServer()
}

func RegisterAIAccountServiceServer(s grpc.ServiceRegistrar, srv AIAccountServiceServer) {
	s.RegisterService(&AIAccountService_ServiceDesc, srv)
}

func _AIAccountService_GetBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAccountServiceServer).GetBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAccountService_GetBonus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAccountServiceServer).GetBonus(ctx, req.(*BonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAccountService_ServiceDesc is the grpc.ServiceDesc for AIAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AIAccountService",
	HandlerType: (*AIAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBonus",
			Handler:    _AIAccountService_GetBonus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus_service.proto",
}
