// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: bonus_service.proto

package bonus_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BonusService_GetBonus_FullMethodName = "/BonusService/GetBonus"
)

// BonusServiceClient is the client API for BonusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BonusServiceClient interface {
	GetBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*BonusResponse, error)
}

type bonusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBonusServiceClient(cc grpc.ClientConnInterface) BonusServiceClient {
	return &bonusServiceClient{cc}
}

func (c *bonusServiceClient) GetBonus(ctx context.Context, in *BonusRequest, opts ...grpc.CallOption) (*BonusResponse, error) {
	out := new(BonusResponse)
	err := c.cc.Invoke(ctx, BonusService_GetBonus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BonusServiceServer is the server API for BonusService service.
// All implementations must embed UnimplementedBonusServiceServer
// for forward compatibility
type BonusServiceServer interface {
	GetBonus(context.Context, *BonusRequest) (*BonusResponse, error)
	mustEmbedUnimplementedBonusServiceServer()
}

// UnimplementedBonusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBonusServiceServer struct {
}

func (UnimplementedBonusServiceServer) GetBonus(context.Context, *BonusRequest) (*BonusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBonus not implemented")
}
func (UnimplementedBonusServiceServer) mustEmbedUnimplementedBonusServiceServer() {}

// UnsafeBonusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BonusServiceServer will
// result in compilation errors.
type UnsafeBonusServiceServer interface {
	mustEmbedUnimplementedBonusServiceServer()
}

func RegisterBonusServiceServer(s grpc.ServiceRegistrar, srv BonusServiceServer) {
	s.RegisterService(&BonusService_ServiceDesc, srv)
}

func _BonusService_GetBonus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BonusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BonusServiceServer).GetBonus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BonusService_GetBonus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BonusServiceServer).GetBonus(ctx, req.(*BonusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BonusService_ServiceDesc is the grpc.ServiceDesc for BonusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BonusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BonusService",
	HandlerType: (*BonusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBonus",
			Handler:    _BonusService_GetBonus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bonus_service.proto",
}
