// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: peer_communication.proto

package peer_communication_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERR_CODE_PEER_COMMUNICATION_SERVICE int32

const (
	ERR_CODE_PEER_COMMUNICATION_SERVICE_CODE_NO_ERROR_PEER_COMMUNICATION_SERVICE          ERR_CODE_PEER_COMMUNICATION_SERVICE = 0
	ERR_CODE_PEER_COMMUNICATION_SERVICE_CODE_ERR_MISSING_PARAM_PEER_COMMUNICATION_SERVICE ERR_CODE_PEER_COMMUNICATION_SERVICE = -1
	ERR_CODE_PEER_COMMUNICATION_SERVICE_CODE_ERR_INVALID_PARAM_PEER_COMMUNICATION_SERVICE ERR_CODE_PEER_COMMUNICATION_SERVICE = -2
	ERR_CODE_PEER_COMMUNICATION_SERVICE_CODE_ERR_UNKNOWN_PEER_COMMUNICATION_SERVICE       ERR_CODE_PEER_COMMUNICATION_SERVICE = -1001
)

// Enum value maps for ERR_CODE_PEER_COMMUNICATION_SERVICE.
var (
	ERR_CODE_PEER_COMMUNICATION_SERVICE_name = map[int32]string{
		0:     "CODE_NO_ERROR_PEER_COMMUNICATION_SERVICE",
		-1:    "CODE_ERR_MISSING_PARAM_PEER_COMMUNICATION_SERVICE",
		-2:    "CODE_ERR_INVALID_PARAM_PEER_COMMUNICATION_SERVICE",
		-1001: "CODE_ERR_UNKNOWN_PEER_COMMUNICATION_SERVICE",
	}
	ERR_CODE_PEER_COMMUNICATION_SERVICE_value = map[string]int32{
		"CODE_NO_ERROR_PEER_COMMUNICATION_SERVICE":          0,
		"CODE_ERR_MISSING_PARAM_PEER_COMMUNICATION_SERVICE": -1,
		"CODE_ERR_INVALID_PARAM_PEER_COMMUNICATION_SERVICE": -2,
		"CODE_ERR_UNKNOWN_PEER_COMMUNICATION_SERVICE":       -1001,
	}
)

func (x ERR_CODE_PEER_COMMUNICATION_SERVICE) Enum() *ERR_CODE_PEER_COMMUNICATION_SERVICE {
	p := new(ERR_CODE_PEER_COMMUNICATION_SERVICE)
	*p = x
	return p
}

func (x ERR_CODE_PEER_COMMUNICATION_SERVICE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERR_CODE_PEER_COMMUNICATION_SERVICE) Descriptor() protoreflect.EnumDescriptor {
	return file_peer_communication_proto_enumTypes[0].Descriptor()
}

func (ERR_CODE_PEER_COMMUNICATION_SERVICE) Type() protoreflect.EnumType {
	return &file_peer_communication_proto_enumTypes[0]
}

func (x ERR_CODE_PEER_COMMUNICATION_SERVICE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERR_CODE_PEER_COMMUNICATION_SERVICE.Descriptor instead.
func (ERR_CODE_PEER_COMMUNICATION_SERVICE) EnumDescriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{0}
}

type BlockHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlockHeightRequest) Reset() {
	*x = BlockHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightRequest) ProtoMessage() {}

func (x *BlockHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightRequest.ProtoReflect.Descriptor instead.
func (*BlockHeightRequest) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{0}
}

type BlockHeightReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *CommonRspHeaderPeerCommunicationService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Height int64                                    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *BlockHeightReponse) Reset() {
	*x = BlockHeightReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHeightReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeightReponse) ProtoMessage() {}

func (x *BlockHeightReponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeightReponse.ProtoReflect.Descriptor instead.
func (*BlockHeightReponse) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeightReponse) GetHeader() *CommonRspHeaderPeerCommunicationService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BlockHeightReponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetRecentHeadersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GetRecentHeadersRequest) Reset() {
	*x = GetRecentHeadersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentHeadersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentHeadersRequest) ProtoMessage() {}

func (x *GetRecentHeadersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentHeadersRequest.ProtoReflect.Descriptor instead.
func (*GetRecentHeadersRequest) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecentHeadersRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetRecentHeadersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header            *CommonRspHeaderPeerCommunicationService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncodedHeaderList []byte                                   `protobuf:"bytes,2,opt,name=encoded_header_list,json=encodedHeaderList,proto3" json:"encoded_header_list,omitempty"`
}

func (x *GetRecentHeadersResponse) Reset() {
	*x = GetRecentHeadersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecentHeadersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentHeadersResponse) ProtoMessage() {}

func (x *GetRecentHeadersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentHeadersResponse.ProtoReflect.Descriptor instead.
func (*GetRecentHeadersResponse) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecentHeadersResponse) GetHeader() *CommonRspHeaderPeerCommunicationService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetRecentHeadersResponse) GetEncodedHeaderList() []byte {
	if x != nil {
		return x.EncodedHeaderList
	}
	return nil
}

type ValidatorSetByHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *ValidatorSetByHeightRequest) Reset() {
	*x = ValidatorSetByHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorSetByHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSetByHeightRequest) ProtoMessage() {}

func (x *ValidatorSetByHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSetByHeightRequest.ProtoReflect.Descriptor instead.
func (*ValidatorSetByHeightRequest) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{4}
}

func (x *ValidatorSetByHeightRequest) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type ValidatorSetByHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header               *CommonRspHeaderPeerCommunicationService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	EncodedValidatorList []byte                                   `protobuf:"bytes,2,opt,name=encoded_validator_list,json=encodedValidatorList,proto3" json:"encoded_validator_list,omitempty"`
}

func (x *ValidatorSetByHeightResponse) Reset() {
	*x = ValidatorSetByHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidatorSetByHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorSetByHeightResponse) ProtoMessage() {}

func (x *ValidatorSetByHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorSetByHeightResponse.ProtoReflect.Descriptor instead.
func (*ValidatorSetByHeightResponse) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{5}
}

func (x *ValidatorSetByHeightResponse) GetHeader() *CommonRspHeaderPeerCommunicationService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ValidatorSetByHeightResponse) GetEncodedValidatorList() []byte {
	if x != nil {
		return x.EncodedValidatorList
	}
	return nil
}

type GetCoinOwnerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *GetCoinOwnerRequest) Reset() {
	*x = GetCoinOwnerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinOwnerRequest) ProtoMessage() {}

func (x *GetCoinOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinOwnerRequest.ProtoReflect.Descriptor instead.
func (*GetCoinOwnerRequest) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{6}
}

func (x *GetCoinOwnerRequest) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type GetCoinOwnerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header         *CommonRspHeaderPeerCommunicationService `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AddressInBytes []byte                                   `protobuf:"bytes,2,opt,name=address_in_bytes,json=addressInBytes,proto3" json:"address_in_bytes,omitempty"`
}

func (x *GetCoinOwnerResponse) Reset() {
	*x = GetCoinOwnerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinOwnerResponse) ProtoMessage() {}

func (x *GetCoinOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinOwnerResponse.ProtoReflect.Descriptor instead.
func (*GetCoinOwnerResponse) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{7}
}

func (x *GetCoinOwnerResponse) GetHeader() *CommonRspHeaderPeerCommunicationService {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetCoinOwnerResponse) GetAddressInBytes() []byte {
	if x != nil {
		return x.AddressInBytes
	}
	return nil
}

type CommonRspHeaderPeerCommunicationService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CommonRspHeaderPeerCommunicationService) Reset() {
	*x = CommonRspHeaderPeerCommunicationService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_peer_communication_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRspHeaderPeerCommunicationService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRspHeaderPeerCommunicationService) ProtoMessage() {}

func (x *CommonRspHeaderPeerCommunicationService) ProtoReflect() protoreflect.Message {
	mi := &file_peer_communication_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRspHeaderPeerCommunicationService.ProtoReflect.Descriptor instead.
func (*CommonRspHeaderPeerCommunicationService) Descriptor() ([]byte, []int) {
	return file_peer_communication_proto_rawDescGZIP(), []int{8}
}

func (x *CommonRspHeaderPeerCommunicationService) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *CommonRspHeaderPeerCommunicationService) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_peer_communication_proto protoreflect.FileDescriptor

var file_peer_communication_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x6e, 0x0a, 0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x22, 0x31, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x8c, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x40, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x2e, 0x0a, 0x13, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x11, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x35, 0x0a, 0x1b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53,
	0x65, 0x74, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x1c, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x16,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x82, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x10, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x22, 0x53, 0x0a, 0x27, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x8d, 0x02, 0x0a, 0x23, 0x45, 0x52, 0x52, 0x5f,
	0x43, 0x4f, 0x44, 0x45, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x55, 0x4e,
	0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x12,
	0x2c, 0x0a, 0x28, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4e, 0x4f, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x55, 0x4e, 0x49, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x3e, 0x0a,
	0x31, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x4d, 0x49, 0x53, 0x53, 0x49, 0x4e,
	0x47, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x55, 0x4e, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x43, 0x45, 0x10, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x3e, 0x0a,
	0x31, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4d,
	0x4d, 0x55, 0x4e, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x43, 0x45, 0x10, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x12, 0x38, 0x0a,
	0x2b, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x55, 0x4e, 0x49, 0x43, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x97, 0xf8, 0xff,
	0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x32, 0xae, 0x02, 0x0a, 0x18, 0x50, 0x65, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x13, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x14, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x42, 0x79, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x42, 0x79, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x42, 0x79, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x4f, 0x77, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_peer_communication_proto_rawDescOnce sync.Once
	file_peer_communication_proto_rawDescData = file_peer_communication_proto_rawDesc
)

func file_peer_communication_proto_rawDescGZIP() []byte {
	file_peer_communication_proto_rawDescOnce.Do(func() {
		file_peer_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_peer_communication_proto_rawDescData)
	})
	return file_peer_communication_proto_rawDescData
}

var file_peer_communication_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_peer_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_peer_communication_proto_goTypes = []interface{}{
	(ERR_CODE_PEER_COMMUNICATION_SERVICE)(0),        // 0: ERR_CODE_PEER_COMMUNICATION_SERVICE
	(*BlockHeightRequest)(nil),                      // 1: BlockHeightRequest
	(*BlockHeightReponse)(nil),                      // 2: BlockHeightReponse
	(*GetRecentHeadersRequest)(nil),                 // 3: GetRecentHeadersRequest
	(*GetRecentHeadersResponse)(nil),                // 4: GetRecentHeadersResponse
	(*ValidatorSetByHeightRequest)(nil),             // 5: ValidatorSetByHeightRequest
	(*ValidatorSetByHeightResponse)(nil),            // 6: ValidatorSetByHeightResponse
	(*GetCoinOwnerRequest)(nil),                     // 7: GetCoinOwnerRequest
	(*GetCoinOwnerResponse)(nil),                    // 8: GetCoinOwnerResponse
	(*CommonRspHeaderPeerCommunicationService)(nil), // 9: CommonRspHeaderPeerCommunicationService
}
var file_peer_communication_proto_depIdxs = []int32{
	9, // 0: BlockHeightReponse.header:type_name -> CommonRspHeaderPeerCommunicationService
	9, // 1: GetRecentHeadersResponse.header:type_name -> CommonRspHeaderPeerCommunicationService
	9, // 2: ValidatorSetByHeightResponse.header:type_name -> CommonRspHeaderPeerCommunicationService
	9, // 3: GetCoinOwnerResponse.header:type_name -> CommonRspHeaderPeerCommunicationService
	1, // 4: PeerCommunicationService.BlockHeight:input_type -> BlockHeightRequest
	3, // 5: PeerCommunicationService.GetRecentHeaders:input_type -> GetRecentHeadersRequest
	5, // 6: PeerCommunicationService.ValidatorSetByHeight:input_type -> ValidatorSetByHeightRequest
	7, // 7: PeerCommunicationService.GetCoinOwner:input_type -> GetCoinOwnerRequest
	2, // 8: PeerCommunicationService.BlockHeight:output_type -> BlockHeightReponse
	4, // 9: PeerCommunicationService.GetRecentHeaders:output_type -> GetRecentHeadersResponse
	6, // 10: PeerCommunicationService.ValidatorSetByHeight:output_type -> ValidatorSetByHeightResponse
	8, // 11: PeerCommunicationService.GetCoinOwner:output_type -> GetCoinOwnerResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_peer_communication_proto_init() }
func file_peer_communication_proto_init() {
	if File_peer_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_peer_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHeightReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentHeadersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecentHeadersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorSetByHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidatorSetByHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinOwnerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinOwnerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_peer_communication_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRspHeaderPeerCommunicationService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_peer_communication_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_peer_communication_proto_goTypes,
		DependencyIndexes: file_peer_communication_proto_depIdxs,
		EnumInfos:         file_peer_communication_proto_enumTypes,
		MessageInfos:      file_peer_communication_proto_msgTypes,
	}.Build()
	File_peer_communication_proto = out.File
	file_peer_communication_proto_rawDesc = nil
	file_peer_communication_proto_goTypes = nil
	file_peer_communication_proto_depIdxs = nil
}
